remove dremio and pachctl references
StatCan/kubeflow-containers pull request #115
Opened 2020-09-11 16:54 UTC by saffaalvi

Resolves https://github.com/StatCan/kubeflow-containers/issues/105

2020-09-11 21:27 UTC, ca-scribner requested changes
might be able to remove a few more things.  Not sure if they're used elsewhere though

2020-09-11 21:27 UTC, ca-scribner commented on base-notebook/cpu/Dockerfile
>  RUN conda install --quiet --yes pyodbc && \
do we need the rest of this ODBC stuff or was it only here for Dremio?

2020-09-11 21:27 UTC, ca-scribner commented on base-notebook/gpu/Dockerfile
>  RUN conda install --quiet --yes pyodbc && \
Same comment as above

2020-09-14 15:07 UTC, blairdrummond commented on base-notebook/cpu/Dockerfile
>  RUN conda install --quiet --yes pyodbc && \
I think ODBC is a good idea in case someone wants to connect to an external database. Was needed for Dremio, but I think it's a good idea to have in general.

2020-09-14 16:18 UTC, ca-scribner commented on base-notebook/cpu/Dockerfile
>  RUN conda install --quiet --yes pyodbc && \
I think the ODBC stuff is ~1/2 the total build time for this (just tested locally and assuming it'll be the same online) - adds ~8 min per build.  

To connect to other db's I think users only need to `pip install pyodbc` right?  If so, I vote we remove to keep the rebuilds shorter and let users install when they need it.  @blairdrummond?

2020-09-14 16:21 UTC, ca-scribner commented on base-notebook/cpu/Dockerfile
>  RUN conda install --quiet --yes pyodbc && \
hmm users can't `apt-get install unixodbc-dev` for themselves though and that's a requirement on linux.  

I think most of the slowness here comes from conda - we could `apt-get install unixodbc-dev` then `pip install pyodbc` instead as a compromise

2020-09-14 19:24 UTC, ca-scribner reviewed
Looks good to me

2020-09-15 15:10 UTC, ca-scribner approved these changes

2020-09-15 15:11 UTC, merged