Test workflow
StatCan/kubeflow-containers pull request #144
Opened 2020-11-03 17:20 UTC by Nancy-Badran

Ignoring the version of debugger .

2020-11-03 19:28 UTC, brendangadd requested changes
Please give this PR a meaningful name and description.

2020-11-03 19:28 UTC, brendangadd commented on .github/workflows/build-cpu.yml
> +      - Test-workflow
We build off master.

2020-11-03 19:28 UTC, brendangadd commented on minimal-notebook/cpu/Dockerfile
> +      '@jupyterlab/debugger' \
Still need to specify the versions like the other extensions.

2020-11-03 19:28 UTC, brendangadd commented on minimal-notebook/cpu/Dockerfile
> +CMD ["start-custom.sh"]
Don't remove trailing newlines.

2020-11-03 19:56 UTC, Nancy-Badran commented on minimal-notebook/cpu/Dockerfile
> +      '@jupyterlab/debugger' \
if I specify the version , it will create a conflict with the jupyterlab extension version . So I choose to ignore the version ?

2020-11-10 22:15 UTC, brendangadd commented on minimal-notebook/cpu/Dockerfile
> +      '@jupyterlab/debugger' \
The package still needs to be resolved to _some_ version, and I would expect any dependency compatibility verification to occur after that resolution has happened. If leaving off the version fixes the error, then maybe specify whatever that default version is.

2020-11-17 14:13 UTC, closed without merging