Short haches
StatCan/kubeflow-containers pull request #145
Opened 2020-11-03 19:24 UTC by Nancy-Badran

2020-11-09 17:14 UTC, sylus commented on .github/workflows/build-cpu.yml
> +      - Short-Haches
Can we remove this branch, it should only happen on master? Assume just for testing?

Also is spelled wrong, should be hashes

2020-11-09 17:26 UTC, Nancy-Badran commented on .github/workflows/build-cpu.yml
> +      - Short-Haches
Yeah, I was testing the short sha ,

2020-11-26 18:03 UTC, brendangadd requested changes
Let's use eight characters.
* `git rev-parse --short` defaults to seven
* GitLab uses eight

2020-11-30 19:35 UTC, sylus commented
I think this needs to be rebased from latest?

2020-11-30 19:45 UTC, Nancy-Badran commented
Yeah @sylus , I will rebase it from latest, thanks

2020-12-07 18:50 UTC, Nancy-Badran commented
workflow changed, proposed changes in PR are out of date

2020-12-07 18:51 UTC, closed without merging