feat(jupyterlab): upgrade and set jupyterlab default language
StatCan/kubeflow-containers pull request #188
Opened 2021-01-12 19:26 UTC by JessicaBarh

Resolves #148 

Translations are done through crowdin. We will need those to be completed before we can use the language pack. https://crowdin.com/project/jupyterlab

2021-01-12 19:28 UTC, JessicaBarh commented
Several extensions were also upgraded so resolve conflicts with new Jupyterlab version. Extensions that were causing conflicts because of Jupyterlab 3.0.3 were commented out for the time being until a new compatible version is released

2021-01-13 13:59 UTC, blairdrummond commented
Looks like the git extension is hoping to add lacalization in 1.0 , so that's promising

https://github.com/jupyterlab/jupyterlab-git/milestone/15

2021-01-13 18:18 UTC, sylus commented
This can't be merged until all extensions work, can we mark this as a Draft?

Thanks!

2021-01-13 19:12 UTC, blairdrummond commented
Extensions which are currently not working

(Checklist is hard to see in dark mode)

- [ ] `# '@ijmbarr/jupyterlab_spellchecker@0.2.0'`
- [ ] `# '@lckr/jupyterlab_variableinspector@0.5.1'`
- [ ] `# '@jupyterlab/github@2.0.0'`
- [ ] `# '@jupyterlab/git@0.23.3'`
- [ ] `# 'jupyterlab-execute-time@1.0.0'`
- [ ] `# 'jupyterlab-theme-solarized-dark@1.0.4'`
- [ ] `# 'jupyterlab-spreadsheet@0.3.2'`
- [ ] `# 'kubeflow-kale-labextension@0.6.0'`
- [ ] `# 'nbdime-jupyterlab@2.0.1'`

2021-01-13 19:25 UTC, JessicaBarh commented
jupyterlab-toc was also removed because it's installed with the core JupyterLab extensions -> https://github.com/jupyterlab/jupyterlab-toc#jupyterlab-toc 

git 0.23.3 was just released 20 days ago so i figured it would be compatible with Jupyterlab 3.0...I'll look into that though

2021-01-20 18:44 UTC, JessicaBarh commented
jupyterlab-lsp and jupyterlab_variableinspector extensions have been removed because there are not offered in french. See
https://github.com/StatCan/kubeflow-containers/issues/148#issuecomment-762985371  for other extensions details

2021-01-20 19:16 UTC, ca-scribner commented
Do jupyterlab-lsp and jupyterlab_variableinspector have any language-specific content?  I think they just serve the existing docstrings.  The docstrings are unilingual, but that doesn't change if we remove these extensions (eg: access them via `help(myfunction)`).  Do these extensions have anything frontend that will offend for official languages?  

It would be nice to leave them in.  @sylus raised the point that they're in use now and we'll get complaints if we remove. 
 @brendangadd thoughts?

2021-01-20 19:25 UTC, JessicaBarh commented
> Do jupyterlab-lsp and jupyterlab_variableinspector have any language-specific content? I think they just serve the existing docstrings. The docstrings are unilingual, but that doesn't change if we remove these extensions (eg: access them via `help(myfunction)`). Do these extensions have anything frontend that will offend for official languages?
> 
> It would be nice to leave them in. @sylus raised the point that they're in use now and we'll get complaints if we remove.
> @brendangadd thoughts?

for lsp there's the settings that are in english and for variable inspector it's the column names. It's all minor stuff

2021-01-20 22:02 UTC, JessicaBarh commented
@bokeh/jupyter_bokeh 2.0.3
@jupyter-widgets/jupyterlab-manager 2.0.0
jupyterlab-dash 0.3.0

are installed from upstream and are outdated so they'll also need to be removed...
 @sinkinsona @sylus

2021-01-20 22:24 UTC, saffaalvi requested changes
Translations look good, both from going through the settings > languages and setting through `start-custom.sh`.

The extensions that @JessicaBarh mentioned above need to be looked at before approving this since they're outdated and don't seem to be compatible. Not sure if they completely work because of this. 

```
$ jupyter labextension list
Config option `kernel_spec_manager_class` not recognized by `ListLabExtensionsApp`.
[W 2021-01-20 21:45:59.067 LabApp] Config option `kernel_spec_manager_class` not recognized by `LabApp`.
JupyterLab v3.0.5
Other labextensions (built into JupyterLab)
  app dir: /opt/conda/share/jupyter/lab
    @bokeh/jupyter_bokeh v2.0.3 enabled  X
    @hadim/jupyter-archive v3.0.0 enabled OK
    @jupyter-widgets/jupyterlab-manager v2.0.0 enabled  X
    @jupyterlab/server-proxy v2.1.2 enabled OK
    @jupyterlab/toc v5.0.3 enabled OK
    @jupyterlab/translation-extension v3.0.2 enabled OK
    jupyter-matplotlib v0.7.4 enabled OK
    jupyterlab-dash v0.3.0 enabled  X
    jupyterlab-plotly v4.14.3 enabled OK
    nbdime-jupyterlab v2.1.0-beta.1 enabled OK
  The following extension are outdated:
    @bokeh/jupyter_bokeh
    @jupyter-widgets/jupyterlab-manager
    jupyterlab-dash
  Consider running "jupyter labextension update --all" to check for updates.
```

2021-01-21 20:48 UTC, brendangadd commented
The only extensions that jump out at me with a red flag are LSP and Git.
* If I'm not mistaken, the autocomplete is awful without LSP
* Git needs no explanation

Do we have an ETA on git extension 1.0 with i18n? And do we know if French will be included in that release?

2021-01-21 21:16 UTC, JessicaBarh commented
> The only extensions that jump out at me with a red flag are LSP and Git.
> 
> * If I'm not mistaken, the autocomplete is awful without LSP
> * Git needs no explanation
> 
> Do we have an ETA on git extension 1.0 with i18n? And do we know if French will be included in that release?

So keep LSP for now? 
Git for JLab 3 is in progress, there's a beta version of the server extension that has just been released and yes there's the french translation available for Git.

2021-01-21 21:48 UTC, sylus commented
Can we have an updated markdown table that shows each extension, status and some notes? Might make it easier to track especially if i want to add i18n to an extension myself. Thanks!

2021-01-21 22:57 UTC, JessicaBarh commented
> Can we have an updated markdown table that shows each extension, status and some notes? Might make it easier to track especially if i want to add i18n to an extension myself. Thanks!

just updated the table on the issue with some notes! I wouldn't mind adding the translation for lsp and archive extensions if you could point me to the right direction. The official language pack is not released so I created my own version [here](https://github.com/StatCan/kubeflow-containers/blob/bc4e092d88e7cd12904e40e3c02f758312fb363b/docker-bits/6_JupyterLab.Dockerfile#L70)  @sylus

2021-01-22 16:50 UTC, brendangadd commented
Suggested course of action:
* Use @blairdrummond's idea of maintaining an OL-compliance branch for a while
* In that branch, start with a **completely** compliant image and build up from there
* Only pull the trigger on replacing our non-compliant images (merge to master) when we need to for release
* Notify our users that this is going to happen
* Publish at least one additional image early in the process so users can run it and know what to expect

Then we can push discussions around inclusion of almost-compliant features closer to the deadline, and we can tackle the i18n of non-compliant components one step at a time.

@ca-scribner Does this, or something similar, seem reasonable?

2021-01-22 17:09 UTC, ca-scribner commented
Yeah makes sense to me. If we get to the point where we are maintaining OL
and non-OL over time it might be a pain, but hopefully we don’t hit that

On Fri, Jan 22, 2021 at 11:50 brendangadd <notifications@github.com> wrote:

> Suggested course of action:
>
>    - Use @blairdrummond <https://github.com/blairdrummond>'s idea of
>    maintaining an OL-compliance branch for a while
>    - In that branch, start with a *completely* compliant image and build
>    up from there
>    - Only pull the trigger on replacing our non-compliant images (merge
>    to master) when we need to for release
>    - Notify our users that this is going to happen
>    - Publish at least one additional image early in the process so users
>    can run it and know what to expect
>
> Then we can push discussions around inclusion of almost-compliant features
> closer to the deadline, and we can tackle the i18n of non-compliant
> components one step at a time.
>
> @ca-scribner <https://github.com/ca-scribner> Does this, or something
> similar, seem reasonable?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/StatCan/kubeflow-containers/pull/188#issuecomment-765547041>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ALPFPI455W346WA775SYMQTS3GUGHANCNFSM4V7V5WUQ>
> .
>

2021-01-22 18:14 UTC, ca-scribner commented
actually thinking of it more, not sure which is easier:

* An OL-compliant branch
  * Pros: Easy to compare between OL and non-OL branch (assuming the changes are additive in our docker bits.  It could get more confusing if we need to use different bases, etc)
  * Cons: If we want actual images to be produced, we also need CI for this OL branch
* OL images in master (eg: something like `Jupyterlab-CPU-OL`)
  * Pros: CI needs no change, and because of the template approach we already use this is really easy to do
  * Cons: Might be harder to compare changes, but can still diff between things

I'm fine with both, but think (2) might be easier.  @JessicaBarh can choose which is best

2021-01-22 18:35 UTC, blairdrummond commented
I think the OL v.s. Non-OL docker-bits idea is nice actually. In fact, we could even still build and push the non-OL images into the cluster, and just remove them from the manifest. Maybe?

2021-01-22 18:53 UTC, ca-scribner commented
yeah it feels like an anti-pattern in git, but like a good pattern given our setup

2021-01-22 18:59 UTC, brendangadd commented
> I think the OL v.s. Non-OL docker-bits idea is nice actually. In fact, we could even still build and push the non-OL images into the cluster, and just remove them from the manifest. Maybe?

Not impossible. :suspect: Partially a question of maintenance. It's something to think about when we're closer to release and evaluating our current/target state gap.

_Why does the `:suspect:` icon look so much like the Doom guy?_

2021-01-22 20:10 UTC, ca-scribner commented
because he was particularly untrusting?

On Fri, Jan 22, 2021 at 1:59 PM brendangadd <notifications@github.com>
wrote:

> I think the OL v.s. Non-OL docker-bits idea is nice actually. In fact, we
> could even still build and push the non-OL images into the cluster, and
> just remove them from the manifest. Maybe?
>
> Not impossible. [image: :suspect:] Partially a question of maintenance.
> It's something to think about when we're closer to release and evaluating
> our current/target state gap.
>
> *Why does the :suspect: icon look so much like the Doom guy?*
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/StatCan/kubeflow-containers/pull/188#issuecomment-765621080>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ALPFPI7VLOQ3GCFJAIL6URLS3HDKLANCNFSM4V7V5WUQ>
> .
>

2021-01-26 15:06 UTC, ca-scribner requested changes
Looks great overall!  Main comments are just to reduce the redundancy.  No need to maintain more than we must :)

2021-01-26 15:06 UTC, ca-scribner commented on scripts/start-custom-OL-compliant.sh
> +        export LANG ="fr_CA.utf8"
Do we need to maintain separate JupyterLab 2.x and 3.x start-custom.sh scripts?  JupyerLab 3 is the only version that will actually show french, but will this `else` statement **break** JupyterLab 2?  If no, I say we just always use this script.

If this content will break JupyterLab 2.x, you could test for the lab version installed (maybe using `conda list` or `pip freeze`?  Or there might be better ways) and then only apply this if JL>=3.0.0.  You could also add an environment variable in the jupyterlab3.Dockerfile (say something like JUPYTERLAB_ALLOW_TRANSLATION=true, or some better name because that seems bad) and then test for that here as part of your if/else)

2021-01-27 14:46 UTC, ca-scribner approved these changes

2021-01-27 15:25 UTC, merged