feat(minio): Automate setup MinIO credentials
StatCan/kubeflow-containers pull request #193
Opened 2021-01-18 17:47 UTC by Nancy-Badran

Resolves #189

2021-01-18 18:00 UTC, blairdrummond requested changes

2021-01-18 18:00 UTC, blairdrummond commented on resources/check-tenant.sh
> +    if [ ! -f /tmp/.minio-$tenant ] || [ /vault/secrets/minio-$tenant-tenant-1 -nt /tmp/.minio-tenant ]; then
This was my bad I think, but there is a missing `$` in the second `.minio-tenant`.

2021-01-18 18:12 UTC, Nancy-Badran commented on resources/check-tenant.sh
> +    if [ ! -f /tmp/.minio-$tenant ] || [ /vault/secrets/minio-$tenant-tenant-1 -nt /tmp/.minio-tenant ]; then
can you plz confirm what I did in https://github.com/StatCan/kubeflow-containers/blob/ee176847b2191bfcdb2de198de06422b93636796/docker-bits/4_CLI.Dockerfile#L46,  to avoid the permission denied on /usr/local/bin/mc

2021-01-18 18:14 UTC, blairdrummond commented on output/JupyterLab-CPU/Dockerfile
> +    && mv mc /usr/local/bin/mc-wrapped \
Yep, this looks right

2021-01-19 14:34 UTC, blairdrummond commented on resources/start-custom.sh
> +cp /check-tenant.sh /usr/local/bin/mc
Have you tested this? I don't think this will work... start-custom.sh does not run as root, so I would not expect this command to have permissions to do this.

2021-01-19 14:35 UTC, blairdrummond commented
Also, you should delete this from the existing code:

https://github.com/StatCan/kubeflow-containers/blob/ee176847b2191bfcdb2de198de06422b93636796/resources/helpers.sh#L4-L11

Your PR basically replaces that functionality

2021-01-19 14:35 UTC, blairdrummond commented on resources/start-custom.sh
> +cp /check-tenant.sh /usr/local/bin/mc
I think you'll need to use a COPY in the Docker files

2021-01-19 14:43 UTC, Nancy-Badran commented on resources/start-custom.sh
> +cp /check-tenant.sh /usr/local/bin/mc
yeah , it give me a permission denied , so I used COPY in Dockerfile and change the mode of access to /usr/local/bin/mc, but I didnt delete it from start-custom.sh . Ok So I will delete the` cp /check-tenant.sh /usr/local/bin/mc` from the start bash.

2021-01-19 16:36 UTC, ca-scribner requested changes
Note: I accidentally wrote comments on `output/RStudio/check-tenant.sh` but they're supposed to be on `resources/check-tenant.sh`.  Read it as if I meant to edit `resources/check-tenant.sh` please :)

2021-01-19 16:36 UTC, ca-scribner commented on docker-bits/4_CLI.Dockerfile
> +    && mv mc /usr/local/bin/mc-wrapped \
I think we could be clearer with the name here.  `mc-wrapped` suggests it is actually wrapped already, whereas we are renaming it so we can wrap it later.  Maybe `mc-original` or something like that?

2021-01-19 16:36 UTC, ca-scribner commented on output/RStudio/check-tenant.sh
> +#!/bin/bash
Should we rename this to be clearer of the purpose, and be clearer about purpose in the top line of the script? `check-tenant.sh` doesn't to me say "I am a replacement wrapper for `mc` that will update minio tenants if they are stale before running". I think someone glancing at this file quickly wont realize you should run your `mc` commands through it, unless maybe they catch the call to `mc-wrapped` on the last line (and know what `mc-wrapped` is)

Maybe call it `mc-tenant-wrapper.sh` or something like that? And then a good first line comment in the file that says exactly how this is used.

2021-01-19 16:36 UTC, ca-scribner commented on output/RStudio/check-tenant.sh
> +    if [ ! -f /tmp/.minio-$tenant ] || [ /vault/secrets/minio-$tenant-tenant-1 -nt /tmp/.minio-$tenant ]; then
How does this handle `minio-$tenant-tenant-1` files that are missing? I can think of three cases

1. minio-standard-tenant-1 exists, minio-premium-tenant-1 does not exist
2. minio-standard-tenant-1 does not exist, minio-premium-tenant-1 exists
3. minio-standard-tenant-1 does not exist, minio-premium-tenant-1 does not exist

I'm not 100% sure what will happen in these scenarios, but my gut says at least one will break. The behaviour I think we want is that any missing/corrupt file will be skipped without affecting the others.  I could see either if the first file is missing that the second doesn't get updated, or that if the second is missing that it will actually get overwritten by the first

2021-01-19 16:36 UTC, ca-scribner commented on output/RStudio/check-tenant.sh
> +for tenant in standard premium; do
Should we explicitly list these tenants here, or should we loop over files matching a pattern? Something like loop over all `/vault/secrets/minio-*`. That way we don't have to modify this later

2021-01-19 16:36 UTC, ca-scribner commented on output/RStudio/check-tenant.sh
> +        mc config host add $tenant $MINIO_URL $MINIO_ACCESS_KEY $MINIO_SECRET_KEY
We should name the `$tenant` here the same as they are named in the mounted directories under `~/minio/*`. Those directories right now are given the full name, eg: `standard-tenant-1`.

2021-01-19 18:59 UTC, Nancy-Badran commented on output/RStudio/check-tenant.sh
> +for tenant in standard premium; do
yeah I will do  it to loop over `/vault/secrets/minio-*`

2021-01-19 19:33 UTC, Nancy-Badran commented on output/RStudio/check-tenant.sh
> +        mc config host add $tenant $MINIO_URL $MINIO_ACCESS_KEY $MINIO_SECRET_KEY
In /vault/secrets/minio-* it is already named as same as they are named in mounted directories , I will rename it also in /tm/*

2021-01-19 20:06 UTC, ca-scribner commented on output/RStudio/check-tenant.sh
> +        mc config host add $tenant $MINIO_URL $MINIO_ACCESS_KEY $MINIO_SECRET_KEY
yeah I think a nice benefit of looping over the files in the dir is you'll get the same full names as what are mounted in `~/minio`

2021-01-19 20:08 UTC, ca-scribner commented on output/RStudio/check-tenant.sh
> +for tenant in standard premium; do
I'm sure you'll catch it on implementation, but all the files have two copies (one using environment variables, one written in JSON), so you'll have to filter to only handle one of the two

2021-01-22 18:52 UTC, ca-scribner requested changes

2021-01-22 18:52 UTC, ca-scribner commented on Makefile
> +	cp -r  resources/* $(OUT)/$@
tiny thing - there's a double space here before resources instead of single

2021-01-22 18:52 UTC, ca-scribner commented on docker-bits/4_CLI.Dockerfile
> +    && echo "${OH_MY_ZSH_SHA} /tmp/oh-my-zsh-install.sh" | sha256sum -c
was this an intentional change to remove the helpers.sh?  Just seems unconnected so asking to make sure.  If this was intentional, sounds good to me

2021-01-22 18:52 UTC, ca-scribner commented on output/RStudio/mc-tenant-wrapper.sh
> +for  f in $(ls /vault/secrets/minio-* | grep -v json); do
We can make this more robust.  We want to find files with no file extension.  This filters out files ending in `.json`, but what if there were others?  If we add a `.yaml` file here for some other application, we'll break this wrapper unexpectedly.  I think you can more directly find the files you're looking for.

One idea is to `grep -v -E '\..*'`, which I think would match anything that does not have have an extension.  Another is to use `find . -type f ! -name "*.*"` which finds only files without extensions

2021-01-22 18:52 UTC, ca-scribner commented on output/RStudio/mc-tenant-wrapper.sh
> + tenant=$(basename "$f" | sed 's/.json$//' | sed 's/^minio-//') # remove the json suffix and minio- prefix
With a finer search for the for loop above, the `sed` for json can be removed here

2021-01-22 18:52 UTC, ca-scribner commented on output/RStudio/mc-tenant-wrapper.sh
> +     touch /tmp/.minio-$tenant
this should really be in a subshell, I think like this:

```
(
  source $f
  mc config host add $tenant $MINIO_URL $MINIO_ACCESS_KEY $MINIO_SECRET_KEY
)
```

Since we're using environment variables to pass info from `source $f` to the `mc` command, we should use a subshell to avoid accidentally putting those variables in the current shell.  This wont matter most of the time, but if something goes wrong I think it could

2021-01-22 18:52 UTC, ca-scribner commented on output/RStudio/mc-tenant-wrapper.sh
> +     mc config host add $tenant $MINIO_URL $MINIO_ACCESS_KEY $MINIO_SECRET_KEY
have you tried running this script, which calls `mc config ...`, in a built container?  I think this is going to make an infinite recursive loop, because `mc` is this script.  I believe you want to call `/usr/local/bin/mc-wrapped`?

2021-01-22 18:52 UTC, ca-scribner commented on output/RStudio/mc-tenant-wrapper.sh
> +/usr/local/bin/mc-wrapped $@
Put `/usr/local/bin/mc-wrapped` into a variable at the top, that way it is really clear.  Something like `mc_executable=/usr/local/bin/mc-wrapped`, then you can later invoke that here (and if I'm right about the recursion problem above, there as well)

2021-01-22 18:52 UTC, ca-scribner commented on resources/start-custom.sh
> +    #cat /tmp/helpers.sh >> /home/$NB_USER/.zshrc
same question as above for helpers.  Intentional change?

2021-01-22 19:10 UTC, brendangadd commented on docker-bits/4_CLI.Dockerfile
> +    && echo "${OH_MY_ZSH_SHA} /tmp/oh-my-zsh-install.sh" | sha256sum -c
Please preserve trailing newlines.

2021-01-22 19:16 UTC, brendangadd commented on docker-bits/∞_CMD.Dockerfile
> +RUN chmod a+rx /usr/local/bin/mc
Does `COPY` preserve the file mode? Can we set the correct mode on the file in the repo and avoid the `chmod`? /cc @blairdrummond

2021-01-22 19:23 UTC, Nancy-Badran commented on docker-bits/∞_CMD.Dockerfile
> +RUN chmod a+rx /usr/local/bin/mc
I think yeah, COPY preserve the file mode so we can avoid to change mode here

2021-01-22 19:24 UTC, blairdrummond commented on docker-bits/∞_CMD.Dockerfile
> +RUN chmod a+rx /usr/local/bin/mc
Yep COPY should preserve file mode

2021-01-22 19:25 UTC, blairdrummond commented on resources/start-custom.sh
> +    #cat /tmp/helpers.sh >> /home/$NB_USER/.zshrc
This is intentional I think, but should be removed not just commented out

2021-01-22 19:29 UTC, blairdrummond commented on output/RStudio/mc-tenant-wrapper.sh
> +     touch /tmp/.minio-$tenant
Actually I think this would be fine, unless you called `source /usr/local/bin/mc`, if I'm not mistaken. I think exports run within this script wouldn't affect the calling shell

2021-01-22 19:30 UTC, blairdrummond commented on output/RStudio/mc-tenant-wrapper.sh
> +     touch /tmp/.minio-$tenant
Test:

```
$ cat test.sh
#!/bin/sh

export HEY=hey
echo $HEY
```

```
$ ./test.sh
hey
$ echo $HEY

```

2021-01-22 19:31 UTC, brendangadd commented on output/JupyterLab-Tensorflow/mc-tenant-wrapper.sh
> +     source $f
Isn't this going to force the user's env to contain the lexicographically last tenant's variables? If so, as a result, wouldn't the following happen?
* User interacts with minimal tenant
* Creds are updated
* Environment transparently references premium tenant
* User sees no break in connectivity, but doesn't recognize MinIO state

2021-01-22 19:40 UTC, ca-scribner commented on resources/mc-tenant-wrapper.sh
> +/usr/local/bin/mc-wrapped $@
this name is outdated.  Sync it up with what is in the `Dockerfile` :)

2021-01-22 19:41 UTC, Nancy-Badran commented on resources/mc-tenant-wrapper.sh
> +/usr/local/bin/mc-wrapped $@
oops yeah

2021-01-26 14:46 UTC, Nancy-Badran commented on output/RStudio/mc-tenant-wrapper.sh
> +     mc config host add $tenant $MINIO_URL $MINIO_ACCESS_KEY $MINIO_SECRET_KEY
@ca-scribner , In fact I am not 100% sur that it will not loop since `config host add ...`  must call the original mc copied to  /usr/local/bin/mc-original. For testing, if I will test it locally in a running container , as you know, I cant access to /vault/secrets/minio-* since the minio credentials are managed by vault and injected via a k8s pod, if I am not wrong, and if I test it in a running notebook server the /usr/local/bin/mc-original will not be there, and must to call it somewhere, so it will not a good way to ensure that the bash script will not loop . Do you have another way to do the test?

2021-01-26 17:06 UTC, ca-scribner commented on output/RStudio/mc-tenant-wrapper.sh
> +     mc config host add $tenant $MINIO_URL $MINIO_ACCESS_KEY $MINIO_SECRET_KEY
Some ideas for testing:
* build/run the docker image locally
* create your own /vault/secrets/* files (vault would normally mount these files, but they're just text files so you can create them yourself.  Or, you can add a `COPY` at the end of your Dockerfile to debug (then remove it later)
* see what it does

You also don't actually need to access those files.  You can mock that part out of your script (just comment out the things that needed that file at the top of your script during testing).  You need to decide if the `mc` call will recurse or actually get to the original `mc` tool - the `mc` host doesn't need to be real (if you get to the real `mc` tool it'll break saying a host doesn't exist.  If you recurse, you'll never get there)

In general, this is a good case for mocking (eg: faking, like putting your own files in `/vault/*` rather than using real ones mounted by Vault) or commenting out unimportant pieces of the system that you can't easily test with.

2021-01-26 21:02 UTC, Nancy-Badran commented on output/RStudio/mc-tenant-wrapper.sh
> +     mc config host add $tenant $MINIO_URL $MINIO_ACCESS_KEY $MINIO_SECRET_KEY
Create file with credential and copy it from Dockerfile to /vault/secrets/minio-* . I can tell you it doesn't loop from my side.

2021-01-27 21:27 UTC, ca-scribner approved these changes

2021-02-01 16:01 UTC, ca-scribner commented on docker-bits/4_CLI.Dockerfile
> -COPY helpers.sh /tmp/helpers.sh
I don't think the intent was to remove helpers entirely.  My guess is this comes from a comment from Blair about removing just the mc-related part of the helpers script?

2021-02-01 16:31 UTC, merged