update: docker-stack base image version
StatCan/kubeflow-containers pull request #206
Opened 2021-02-01 18:12 UTC by JessicaBarh

2021-02-02 18:41 UTC, JessicaBarh commented
using the new Docker-stacks image that includes JupyterLab 3.0, there are now issues in the tensorflow images when installing tensorflow-gpu. It tries to install using channel conda-forge but it should be using "defaults" (pkgs/main/linux-64) see [CI build.](https://github.com/StatCan/kubeflow-containers/runs/1809894941#step:6:825)

running `cat .condarc ` does not show defaults in the list of channels but running `conda config --append channels defaults` returns "'defaults' already in 'channels' list, moving to the bottom"

2021-02-03 02:49 UTC, JessicaBarh commented
_tensorflow-gpu_ version installed in our original JupyterLab-Tensorflow image (JLab 2) using conda is outdated - **1.14.0** 
Changed it to use pip to install latest version - **2.4.1** in both OL and non-OL Tensorflow images

2021-02-04 14:42 UTC, ca-scribner requested changes

2021-02-04 14:42 UTC, ca-scribner commented on .github/workflows/build.yaml
> +        fi
This would be a temporary change while we maintain two streams, one using an older docker-stacks and one using the newest one?

2021-02-04 14:42 UTC, ca-scribner commented on .github/workflows/build.yaml
> +        fi
If yes, let's add a comment in here (and push.yaml) to reflect that just so it is clear.  Something that states this is temporary and the condition on which we should remove it (that way when we **do** forget to remove it and then notice this in months, we know what to do).  Maybe like "Temporary fix to support ..." or such.  

Let's also combine this with the `COMMIT=` on 57 and add an echo statement in this if block that say we're overriding `COMMIT`.  I'm thinking something like
```
if is OL-compliant; then
  # Temporary special case to address ... (this is the statement where you can say why we did this and when it should be removed, etc)
   ...
else
  # Typical case
  COMMIT=$(make get-commit)
fi
```

2021-02-04 14:42 UTC, ca-scribner commented on docker-bits/0_CPU-OL-compliant.Dockerfile
> +ARG BASE_VERSION=r-4.0.3
As an alternative to hard-coding the docker version override in the Makefile, you could also put it here.  You could ignore `BASE_VERSION` and just hard-code to r-4.0.3.  Not sure it is a better way just mentioning it.

2021-02-04 14:42 UTC, ca-scribner commented on docker-bits/2_Tensorflow.Dockerfile
> -    fix-permissions /home/$NB_USER
These commands always need to be included no matter what when we `pip` or `conda` install anything.  They change the permissions of the contents of the `conda_dir` (which includes where `pip` installs things) to be writable by the `jovyan` user.  This is important to make python usable (otherwise people can't modify their packages).  

They also have to be in the same `RUN` command (they can't be something like `RUN pip install ... ; RUN fix-permissions`).  If they're not done in the same `RUN`, but instead done later, because of how Docker handles layers it'll actually duplicate all the data!  Because of that, by leaving it out here entirely, the next time someone does a `fix-permissions` somewhere later in the Dockerfiles it'll add a surprise 2-3GB to their image.

2021-02-04 14:42 UTC, ca-scribner commented on docker-bits/3_Kubeflow.Dockerfile
> +      'kubeflow-metadata==0.2.0' \
Do you know what the error was here that forced this change?  I think reverting breaks something (can't remember what, but I remember **something** breaking ;)  ).  Maybe we can fix the problem and keep the higher versions

2021-02-04 16:23 UTC, JessicaBarh commented on docker-bits/3_Kubeflow.Dockerfile
> +      'kubeflow-metadata==0.2.0' \
Using kubeflow-metadata==0.3.1 and ml-metadata==0.26.0 gave:
```
ERROR: Cannot install kubeflow-metadata==0.3.1 and ml-metadata==0.26.0 because these package versions have conflicting dependencies.
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies
```

2021-02-04 16:30 UTC, JessicaBarh commented on docker-bits/3_Kubeflow.Dockerfile
> +      'kubeflow-metadata==0.2.0' \
so ml-metadata==0.27.0 and ml-metadata==0.2.0 works too

2021-02-04 20:25 UTC, ca-scribner commented on docker-bits/0_CPU-OL-compliant.Dockerfile
> +FROM jupyter/datascience-notebook:r-4.0.3
Please add a comment here noting how this is temporary and overrides the usual behaviour etc etc

2021-02-04 20:25 UTC, ca-scribner approved these changes

2021-02-04 20:53 UTC, merged