fix: repo build errors and vscode issues
StatCan/kubeflow-containers pull request #252
Opened 2021-05-10 19:20 UTC by JessicaBarh

# Description

* Fixes repo build errors (vulnerabilities and unpinned upstream image causing a dependency conflict)
* Fixes vscode not showing in french and having broken python support 

Resolves #249, #247, #240 also #257

# Tests / Quality Checks

## Automated Testing/build and deployment
- [x] Does the image pass CI successfully (build, pass vulnerability scan, and pass automated test suite)?
- [x] If new features are added (new image, new binary, etc), have new automated tests been added to cover these?
- [x] If new features are added that require in-cluster testing (e.g. a new feature that needs to interact with kubernetes), have you added the `auto-deploy` tag to the PR before pushing in order to build and push the image to ACR so you can test it in cluster as a custom image?

## JupyterLab extensions

- [x] Are all extensions "enabled" (`jupyter labextension list` from inside the notebook)?

## VS Code tests

- [x] Does VS Code open?
- [x] Can you install extensions?

## Code review

- [x] Have you added the `auto-deploy` tag to your PR before your most recent push to this repo?  This causes CI to build the image and push to our ACR, letting reviewers access the built image without having to create it themselves
- [x] Have you chosen a reviewer, attached them as a reviewer to this PR, and messaged them with the SHA-pinned image name for the final image to test (e.g. `k8scc01covidacr.azurecr.io/machine-learning-notebook-cpu:746d058e2f37e004da5ca483d121bfb9e0545f2b`)?

2021-05-11 21:01 UTC, ca-scribner requested changes
otherwise lgtm

2021-05-11 21:01 UTC, ca-scribner commented on Makefile
> +DOCKER-STACKS-UPSTREAM-DIGEST := @sha256:aec9bf3915d209b42bf67b1914d3e8d1418e052c451d76577cfd6b05f7b5bbcd
Since we're already changing this, let's put this back to just using the tag and update that tag

```suggestion
# Note: docker-stacks uses version tags (eg: `r-4.0.3`) to specify stacks that may be updated over time
# We must pin to the git SHA tagging scheme, NOT the version, otherwise upstream will change without notice
DOCKER-STACKS-UPSTREAM-TAG := 512afd49b925
```

2021-05-11 21:01 UTC, ca-scribner commented on Makefile
> +	@echo $(DOCKER-STACKS-UPSTREAM-TAG)$(DOCKER-STACKS-UPSTREAM-DIGEST)
Related to tag change above
```suggestion
	@echo $(DOCKER-STACKS-UPSTREAM-TAG)
```

2021-05-11 21:03 UTC, ca-scribner commented on docker-bits/∞_CMD.Dockerfile
> +# Remove libpdfbox-java due to CVE-2019-0228
Can we add the condition on which we'd resolve this, or link a issue or something else that describes this more fully?  I'm just thinking if someone other than us comes to this line two months from now, will they have enough context to understand why this is here and whether we should ever stop removing this package in our images.  Citing the CVE is great but this one in particular had a lot of leaps of (X causes Y causes Z thus do A)

2021-05-11 21:04 UTC, ca-scribner commented on .github/containerscan/allowedlist.yaml
> +    - CVE-2021-23334
Maybe we should add comments here (I think comments work in this file?) that say why each of these is a thing ("CVE allowed because X.  When Y happens we can remove this allowed CVE", etc).

(don't do this for the old CVEs on this list, just for new ones you're adding)

2021-05-12 16:17 UTC, Ito-Matsuda commented
There's some annoying behaviour happening right now with the French Language extension.  It is installed, but vscode is not recognizing it as a "display language" option. Using the older version of the French extension did not work either.
![image](https://user-images.githubusercontent.com/23174198/118007749-6a5e0400-b31a-11eb-8697-f9cf99680484.png)

I _think_ the reason is the languagepacks.json not getting created properly in the /etc/share/code-server/ directory.
Compare our current 
![image](https://user-images.githubusercontent.com/23174198/118009145-cf662980-b31b-11eb-9638-522ef5a343ef.png)

To what I get when I try running locally 
![image](https://user-images.githubusercontent.com/23174198/118009198-dbea8200-b31b-11eb-9c5e-1be71670ba8a.png)

I'll try this out in a bit, as well as maybe make it such that it would use the French file on startup (previously we just installed it and say the LANG variable had no impact on how code-server was starting up)


While not helpful right now, the folks at cdr are looking into doing this sort of thing automatically https://github.com/cdr/code-server/issues/3173

2021-05-12 17:10 UTC, ca-scribner commented
I was going to do a review but I'll hold off on this till Jose reports back :)

2021-05-12 18:06 UTC, Ito-Matsuda commented
All right looks like [we good](https://streamable.com/0icvdd)

2021-05-13 15:33 UTC, ca-scribner reviewed
Added two suggested comments/changes to comments

Also pushed a change moving the libpdfbox-java uninstall up in the stack.  I want CI to build successfully in case I broke something, so I haven't approved yet.  Will approve when that is done

2021-05-13 15:33 UTC, ca-scribner commented on docker-bits/0_Rocker.Dockerfile
> +FROM rocker/geospatial:4.0.3@sha256:9e00ab4fec7b38a0edbadb07e7554bf3b7fa34d15c6fe42522a09ae88d336219
```suggestion
# Rocker/geospatial is tagged by R version number.  They are not clear on whether they'll change those tagged 
# images for hotfixes, so always pin tag and digest to prevent unexpected upstream changes
FROM rocker/geospatial:4.0.3@sha256:9e00ab4fec7b38a0edbadb07e7554bf3b7fa34d15c6fe42522a09ae88d336219
```

2021-05-13 15:33 UTC, ca-scribner commented on docker-bits/0_cpu.Dockerfile
> +# Using the git-SHA is unique and immutable. it can be obtained by running `docker inspect repo/imagename:tag@digest`
```suggestion
# Docker-stacks version tags (eg: `r-4.0.3`) are LIVE images that are frequently updated.  To avoid unexpected
# image updates, pin to the docker-stacks git commit SHA tag.
# It can be obtained by running `docker inspect repo/imagename:tag@digest` or from 
# https://github.com/jupyter/docker-stacks/wiki
```

2021-05-13 21:06 UTC, ca-scribner approved these changes
team effort! :D  lgtm

2021-05-13 21:08 UTC, ca-scribner commented
Leaving for @JessicaBarh to merge once tests pass.  Jess please make sure to squash on merge (I'm terrible at remembering that...)

2021-05-14 03:08 UTC, merged