fix: added PSPP to remote desktop image
StatCan/kubeflow-containers pull request #263
Opened 2021-06-01 13:17 UTC by jumana-s

fix issue #243

2021-06-01 18:20 UTC, blairdrummond commented
@jumana-s can you fix the test error in the CI?

2021-06-01 18:23 UTC, blairdrummond commented on docker-bits/6_remote-desktop.Dockerfile
> +RUN /bin/bash $RESOURCES_PATH/pspp.sh
Take a look at how to clean up layers that install apt packages 

https://github.com/StatCan/kubeflow-containers/blob/0b3c5408fefe76807e4491d29dc096225130acec/docker-bits/6_remote-desktop.Dockerfile#L10-L18

2021-06-01 18:25 UTC, blairdrummond requested changes
Need to fix the test and add `clean-layer.sh` after the install, but otherwise looks good

2021-06-01 18:45 UTC, Ito-Matsuda commented
@jumana-s sorry this _just_ occurred to me but you have to add a `pspp.mo` file to resources/remote-desktop/French/mo-files for the application to appear in French. 
![image](https://user-images.githubusercontent.com/23174198/120374603-c1d30c80-c2e7-11eb-88c6-aab1509fe986.png)

Can get the 1.2.0 PO file from here and then change it into an .MO file.

2021-06-02 15:49 UTC, Ito-Matsuda approved these changes
Looks good to me, has the localization file in the correct spot

2021-06-02 17:05 UTC, blairdrummond approved these changes
LGTM!

2021-06-02 17:07 UTC, merged

2021-06-02 17:14 UTC, blairdrummond commented
@Ito-Matsuda  can you also open up the manifest update once you're ready?

2021-06-03 13:09 UTC, Ito-Matsuda commented
@blairdrummond (good reminder) Yea I can do the manifest update right after Rohan gets his changes in since I don't think that should take too long