Fix: mc command to handles quotes
StatCan/kubeflow-containers pull request #278
Opened 2021-07-07 18:07 UTC by Nancy-Badran

# Description

**fix mc command to handle quotes*

# Tests / Quality Checks

## Automated Testing/build and deployment
- [ ] Does the image pass CI successfully (build, pass vulnerability scan, and pass automated test suite)?
- [ ] If new features are added (new image, new binary, etc), have new automated tests been added to cover these?
- [ ] If new features are added that require in-cluster testing (e.g. a new feature that needs to interact with kubernetes), have you added the `auto-deploy` tag to the PR before pushing in order to build and push the image to ACR so you can test it in cluster as a custom image?

## JupyterLab extensions

- [ ] Are all extensions "enabled" (`jupyter labextension list` from inside the notebook)?

## VS Code tests

- [ ] Does VS Code open?
- [ ] Can you install extensions?

## Code review

- [ ] Have you added the `auto-deploy` tag to your PR before your most recent push to this repo?  This causes CI to build the image and push to our ACR, letting reviewers access the built image without having to create it themselves
- [ ] Have you chosen a reviewer, attached them as a reviewer to this PR, and messaged them with the SHA-pinned image name for the final image to test (e.g. `k8scc01covidacr.azurecr.io/machine-learning-notebook-cpu:746d058e2f37e004da5ca483d121bfb9e0545f2b`)?

2021-07-14 17:45 UTC, brendangadd requested changes

2021-07-14 17:45 UTC, brendangadd commented on output/docker-stacks-datascience-notebook/mc-tenant-wrapper.sh
> +$MC "$@"
I think you can just add quotes: `"$@"` I tested with the following:
```shell
# file: printargs
echo "$# arguments:"
for i in "$@"; do
  echo "> $i"
done

# file: args
PROG=./printargs
$PROG "$@"

# Shell command
$ a=hi
$ ./args one "two $a three" four 'five $a six'
4 arguments:
> one
> two hi three
> four
> five $a six
```

2021-07-15 15:16 UTC, Nancy-Badran commented on output/docker-stacks-datascience-notebook/mc-tenant-wrapper.sh
> +$MC "$@"
if we just add  the quotes like this "$@", it will not works. This is an example of outputs:
```
./fake-mc.sh sql --query "SELECT * FROM s3object s WHERE s.Location like '%Canada%' LIMIT 50" minio/standard-tenant-1/shared/TotalPopulation.csv.gz | head -n 5
/usr/local/bin/mc-original sql --query SELECT * FROM s3object s WHERE s.Location like '%Canada%' LIMIT 50 minio/standard-tenant-1/shared/TotalPopulation.csv.gz
```
We need to keep the quotes in sql command.
This is what we  should have :
```
./fake-mc.sh sql --query "SELECT * FROM s3object s WHERE s.Location like '%Canada%' LIMIT 50" minio/standard-tenant-1/shared/TotalPopulation.csv.gz | head -n 5
/usr/local/bin/mc-original sql --query "SELECT * FROM s3object s WHERE s.Location like '%Canada%' LIMIT 50" minio/standard-tenant-1/shared/TotalPopulation.csv.gz
```

2021-07-28 01:03 UTC, Jose-Matsuda approved these changes
lgtm

2021-08-19 16:27 UTC, brendangadd commented on output/docker-stacks-datascience-notebook/mc-tenant-wrapper.sh
> +$MC "$@"
@Nancy-Badran Just adding quotes works for me, tested in a JupyterLab server.

```
(base) jovyan@jupyter-feb-0:~$ diff /usr/local/bin/mc ./mc
19c19
< $MC $@
---
> $MC "$@"
```
```
(base) jovyan@jupyter-feb-0:~$ /usr/local/bin/mc sql --query "SELECT PopTotal,PopDensity FROM s3object s WHERE s.Location like '%Canada%' LIMIT 50" standard-tenant-1/shared/blair-drummond/sql-example/TotalPopulation.csv.gz | head -3
mc-original: <ERROR> Unable to run sql for PopTotal,PopDensity. Requested file `PopTotal,PopDensity` not found
mc-original: <ERROR> Unable to run sql for FROM. Requested file `FROM` not found
mc-original: <ERROR> Unable to run sql for s3object. Requested file `s3object` not found
mc-original: <ERROR> Unable to run sql for s. Requested file `s` not found
mc-original: <ERROR> Unable to run sql for WHERE. Requested file `WHERE` not found
mc-original: <ERROR> Unable to run sql for s.Location. Requested file `s.Location` not found
mc-original: <ERROR> Unable to run sql for like. Requested file `like` not found
mc-original: <ERROR> Unable to run sql for '%!C(MISSING)anada%!'(MISSING). Requested file `'%Canada%'` not found
mc-original: <ERROR> Unable to run sql for LIMIT. Requested file `LIMIT` not found
mc-original: <ERROR> Unable to run sql for 50. Requested file `50` not found
mc-original: <ERROR> Unable to run sql <source>:0:0: unexpected "<EOF>" (expected "*" | "-" ... | (<number> | <litstring> | ("TRUE" | "FALSE") | "NULL") | <ident> | <quotident> ... | "(" ... | "[" ... | "(" ... | ("AVG" | "MAX" | "MIN" | "SUM" | "COALESCE" | "NULLIF" | "TO_STRING" | "TO_TIMESTAMP" | "UTCNOW" | "CHAR_LENGTH" | "CHARACTER_LENGTH" | "LOWER" | "UPPER") ... | "COUNT" ... | "CAST" ... | "SUBSTRING" ... | "EXTRACT" ... | "TRIM" ... | "DATE_ADD" ... | "DATE_DIFF" ... ... ... ... | "NOT" ... ... ... ... ... ...)
```
```
(base) jovyan@jupyter-feb-0:~$ ./mc sql --query "SELECT PopTotal,PopDensity FROM s3object s WHERE s.Location like '%Canada%' LIMIT 50" standard-tenant-1/shared/blair-drummond/sql-example/TotalPopulation.csv.gz | head -3
13733.398,1.51
14078.449,1.548
14445.453,1.589
```

2021-08-19 16:29 UTC, brendangadd commented on output/docker-stacks-datascience-notebook/mc-tenant-wrapper.sh
> +$MC "$@"
@Nancy-Badran Just adding quotes works for me, tested in a JupyterLab server.

```
(base) jovyan@jupyter-feb-0:~$ diff /usr/local/bin/mc ./mc
19c19
< $MC $@
---
> $MC "$@"
```
```
(base) jovyan@jupyter-feb-0:~$ /usr/local/bin/mc sql --query "SELECT PopTotal,PopDensity FROM s3object s WHERE s.Location like '%Canada%' LIMIT 50" standard-tenant-1/shared/blair-drummond/sql-example/TotalPopulation.csv.gz | head -3
mc-original: <ERROR> Unable to run sql for PopTotal,PopDensity. Requested file `PopTotal,PopDensity` not found
mc-original: <ERROR> Unable to run sql for FROM. Requested file `FROM` not found
mc-original: <ERROR> Unable to run sql for s3object. Requested file `s3object` not found
mc-original: <ERROR> Unable to run sql for s. Requested file `s` not found
mc-original: <ERROR> Unable to run sql for WHERE. Requested file `WHERE` not found
mc-original: <ERROR> Unable to run sql for s.Location. Requested file `s.Location` not found
mc-original: <ERROR> Unable to run sql for like. Requested file `like` not found
mc-original: <ERROR> Unable to run sql for '%!C(MISSING)anada%!'(MISSING). Requested file `'%Canada%'` not found
mc-original: <ERROR> Unable to run sql for LIMIT. Requested file `LIMIT` not found
mc-original: <ERROR> Unable to run sql for 50. Requested file `50` not found
mc-original: <ERROR> Unable to run sql <source>:0:0: unexpected "<EOF>" (expected "*" | "-" ... | (<number> | <litstring> | ("TRUE" | "FALSE") | "NULL") | <ident> | <quotident> ... | "(" ... | "[" ... | "(" ... | ("AVG" | "MAX" | "MIN" | "SUM" | "COALESCE" | "NULLIF" | "TO_STRING" | "TO_TIMESTAMP" | "UTCNOW" | "CHAR_LENGTH" | "CHARACTER_LENGTH" | "LOWER" | "UPPER") ... | "COUNT" ... | "CAST" ... | "SUBSTRING" ... | "EXTRACT" ... | "TRIM" ... | "DATE_ADD" ... | "DATE_DIFF" ... ... ... ... | "NOT" ... ... ... ... ... ...)
```
```
(base) jovyan@jupyter-feb-0:~$ ./mc sql --query "SELECT PopTotal,PopDensity FROM s3object s WHERE s.Location like '%Canada%' LIMIT 50" standard-tenant-1/shared/blair-drummond/sql-example/TotalPopulation.csv.gz | head -3
13733.398,1.51
14078.449,1.548
14445.453,1.589
```

2021-08-19 18:48 UTC, brendangadd approved these changes

2021-08-19 18:49 UTC, merged