add new version of sas from azure storage
StatCan/kubeflow-containers pull request #634
Opened 2024-05-29 20:33 UTC by bryanpaget

This update is to remove the SAS image's dependency on sas4c, which is the older SAS image using SAS 9.4 M7.

I have uploaded SAS 9.4 M8 to an Azure storage container and moved the relevant logic out of sas4c into the AAW SAS image.

Todo:
- [ ] Add secrets for storage account to Github Actions.

2024-06-25 17:37 UTC, mathis-marcotte requested changes

2024-06-25 17:37 UTC, mathis-marcotte commented on docker-bits/6_sas.Dockerfile
> +RUN groupadd -g 1337 supergroup && \
This is reverting a PR I made. Is this actually necessary?

2024-06-25 17:37 UTC, mathis-marcotte commented on docker-bits/6_jupyterlab.Dockerfile
> +RUN pip install --no-cache-dir --quiet \
Is this necessary? It seems irrelevant to the PR

2024-06-25 17:41 UTC, mathis-marcotte requested changes

2024-06-25 17:41 UTC, mathis-marcotte commented on docker-bits/6_sas.Dockerfile
> +WORKDIR /home/sas
We don't have a sas user, so we shouldnt have a home/sas

2024-06-26 12:45 UTC, bryanpaget commented on docker-bits/6_jupyterlab.Dockerfile
> +RUN pip install --no-cache-dir --quiet \
I think we need this

2024-06-26 12:45 UTC, bryanpaget commented on docker-bits/6_sas.Dockerfile
> +WORKDIR /home/sas
Good catch, thank you. It was something leftover from the sas4c image.

2024-06-26 12:46 UTC, bryanpaget commented on docker-bits/6_sas.Dockerfile
> +RUN groupadd -g 1337 supergroup && \
It's just an old branch, I opened the branch before you made those changes, so this branch still had the old stuff. I've made the changes to match the work you did.

2024-06-26 12:49 UTC, bryanpaget commented on docker-bits/6_jupyterlab.Dockerfile
> +RUN pip install --no-cache-dir --quiet \
I think the --no-cache-dir and --quiet flags are necessary but I'm building now without them to see what happens. We tend to use those flags throughout the dockerfiles but not consistently. I remember having a permission error related to the cache dir and when I looked at line 50 I noticed it didn't have the --no-cache-dir flag, so I decided to add it along with --quiet for consistency with other calls to pip install.

2024-06-26 12:55 UTC, mathis-marcotte commented on docker-bits/6_jupyterlab.Dockerfile
> +RUN pip install --no-cache-dir --quiet \
Ok, good enough for me. We can keep those in, just wanted some clarification, thanks!

2024-06-26 12:59 UTC, mathis-marcotte requested changes

2024-06-26 12:59 UTC, mathis-marcotte commented on docker-bits/6_sas.Dockerfile
> -WORKDIR /home/jovyan
Removing the workdir impacts the rest of the dockerfile, mainly the RUN and COPY commands, is this actually a needed change?

2024-06-26 14:11 UTC, bryanpaget commented on docker-bits/6_sas.Dockerfile
> +RUN groupadd -g 1337 supergroup && \
There was another user/permissions error:

Line 33:
``` bash
chown -R sas:sasstaff /usr/local/SASHome --> chown -R jovyan:sasstaff /usr/local/SASHome
```

2024-06-26 14:33 UTC, bryanpaget commented on docker-bits/6_jupyterlab.Dockerfile
> +RUN pip install --no-cache-dir --quiet \
This is the error I was getting. 
``` bash
WARNING: The directory '/home/jovyan/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
```
Context:
``` bash
Step 47/85 : RUN pip install     'git+https://github.com/betatim/vscode-binder' &&     mamba install --quiet --yes -c conda-forge     'pkg-config'     'jupyterlab'     'jupyter_contrib_nbextensions'     'dash'     'plotly'     'ipywidgets'     'markupsafe'     'ipympl'     'pexpect==4.9.0'     'jupyter-resource-usage'     'jupyter-server-proxy==4.2.0'     'jupyterlab-language-pack-fr-fr'     'jupyterlab_execute_time'     'nb_conda_kernels'     'jupyterlab-lsp'     'jupyter-lsp'  &&     jupyter server extension enable --py jupyter_server_proxy &&     jupyter nbextension enable codefolding/main --sys-prefix &&     jupyter labextension enable       '@jupyterlab/translation-extension'       '@jupyterlab/server-proxy'       'nbdime-jupyterlab'     &&     jupyter lab build &&     jupyter lab clean &&   clean-layer.sh &&   rm -rf /home/$NB_USER/.cache/yarn &&   rm -rf /home/$NB_USER/.node-gyp &&   fix-permissions $CONDA_DIR &&   fix-permissions /home/$NB_USER
 ---> Running in dbcc9a6ffc88
WARNING: The directory '/home/jovyan/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
```

2024-06-26 15:51 UTC, bryanpaget commented on docker-bits/6_sas.Dockerfile
> -WORKDIR /home/jovyan
I'll add it back.

2024-06-26 18:10 UTC, mathis-marcotte requested changes
Tried in a notebook on dev and I can't open SAS Studio.
![image](https://github.com/StatCan/aaw-kubeflow-containers/assets/84033116/953c752e-998c-40a2-9eed-8eea8a978e12)

![image](https://github.com/StatCan/aaw-kubeflow-containers/assets/84033116/42284d76-f5bd-401a-9396-9cce25105ca7)

2024-08-09 12:41 UTC, closed without merging